#ifndef DMASTEPGEN_H
#define DMASTEPGEN_H

#include <cstdint>
#include <string>
#include <sys/errno.h>

#include "../module.h"
#include "../../drivers/pin/pin.h"

#include "extern.h"

void createDMAstepgen(void);

class DMAstepgen : public Module
{
  private:

    int mask;

    int jointNumber;              			// LinuxCNC joint number
    std::string step, direction;	 		// physical pins connections
    uint16_t DMAbufferSize;					// DMA buffer size, number of stepgen iterations be call
    int32_t stepBit;                		// position in the DDS accumulator that triggers a step pulse
    volatile int32_t *ptrFrequencyCommand; 	// pointer to the data source where to get the frequency command
    volatile int32_t *ptrFeedback;       	// pointer where to put the feedback
    volatile uint8_t *ptrJointEnable;

    uint8_t stepLength;						// STEP high time in DMA output slots
    uint8_t stepSpace;						// STEP low time in DMA output slots
    uint8_t dirHold;						// direction hold time in DMA output slots
    uint8_t dirSetup;						// direction setup time in DMA output slots

    int32_t *stepDMAbuffer;
    int32_t *stepDMAbuffer_0;
    int32_t *stepDMAbuffer_1;
    int32_t *dirDMAbuffer_0;
    int32_t *dirDMAbuffer_1;

    bool *stepDMAactiveBuffer;
    bool *dirDMAactiveBuffer;

    uint32_t stepMask;						// step and direction pin locations in DR_TOGGLE registers
    uint32_t dirMask;

    bool isEnabled;        					// flag to enable the step generator
    bool dir;								// requested direction of this DMA period
    bool queuedDirection;					// direction after all queued DMA toggles
    bool pendingDirection;
    bool pendingDirectionValue;
    bool directionSetupPending;
    bool isStepping;
    bool hasLastStepFall;

    int32_t frequencyCommand;     			// the joint frequency command generated by LinuxCNC
    int32_t rawCount;             			// current position raw count
    int32_t accumulator;       				// accumulator
  	int32_t	addValue;		  				//accumulator add add value
  	int32_t	minAddValue;
  	int32_t oldaddValue;					// previous accumulator add value
  	int32_t remainder;
  	int32_t prevRemainder;
    uint64_t bufferStartSlot;				// absolute DMA output slot of the writable buffer
    uint64_t lastStepFallSlot;
    uint64_t pendingStepFallSlot;
    uint64_t pendingDirectionSlot;
    uint64_t directionSetupEndSlot;

    void selectWriteBuffer();
    void advanceDdsWithoutStep();
    void makeStep(
        uint32_t,
        uint64_t,
        uint64_t);

  public:

    DMAstepgen(int32_t, int, std::string, std::string, int, int, volatile int32_t&, volatile int32_t&, volatile uint8_t&, uint8_t, uint8_t, uint8_t, uint8_t);  // constructor

    Pin *stepPin, *directionPin, *debug;		// class object members - Pin objects

    virtual void update(void);           // Module default interface
    virtual void updatePost(void);
    virtual void slowUpdate(void);
    void makePulses();
    void stopPulses();
    void setEnabled(bool);
};


#endif
